apiVersion: batch.volcano.sh/v1alpha1
kind: Job
metadata:
  name: ml-job-new
spec:
  minAvailable: 1
  schedulerName: volcano
  priorityClassName: high-priority
  policies:
    - event: PodEvicted
      action: RestartJob
  plugins:
    ssh: []
    env: []
    svc: []
  maxRetry: 5
  queue: default
  tasks:
    - replicas: 2
      name: "ml-volcano-job"
      template:
        metadata:
          name: web
        spec:
          containers:
            - image: amaurya07/xenonimagenew:1
              imagePullPolicy: IfNotPresent
              name: ml-image
              resources:
                requests:
                  cpu: "0.5"
          restartPolicy: OnFailure
